### ISSUE TITLE
Do not explicitly set defaults for paramset

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3cluster#7]
Many learners explicitly set the param set values to their defaults, e.g. in https://github.com/mlr-org/mlr3cluster/blob/master/R/LearnerClustKMeans.R#L46. This is not necessary. Also, every deviation from the default behavior should be documented on the learner's man page

**Comment by damirpolat** [comment]
Are you referring to `algorithm = "Hartigan-Wong", iter.max = 10L, trace = 0L` part of this? 
If so, they are the defaults in `stats::kmeans`. I just set them explicitly so that when users type `learner$param_set$values` after creating the learner, they could see the defaults. Should this be removed?

**Comment by mllg** [comment]
Yes this is not necessary and we don't do this for other learners. If the user wants to see the defaults, they are printed by the print method of the param set.

**Comment by damirpolat** [comment]
Makes sense. I fixed that in 0d91f96ce2322b5d38a8acefad3f29891ecc0a67.

Thanks, 
Damir
